import { AssetFormDetails } from "./asset-details";

/* eslint-disable @typescript-eslint/naming-convention */
export interface Asset {
    scheduleTrxId: string;
    abbreviation: string;
    adviceDate: string;
    approvedAt: string;
    approvedBy: string;
    approvedNotes: string;
    assetId: string;
    photo: string;
    offlinePhoto: string;
    assetNumber: string;
    assetStatusId: string;
    assetStatusName: string;
    condition: string;
    merk: string;
    capacityValue: string;
    detailLocation: string;
    unitCapacity: string;
    supplyDate: string;
    reportPhoto: string;
    scannedAccuration: string;
    scannedAt: string;
    scannedBy: string;
    scannedEnd: string;
    scannedNotes: string;
    scannedWith: string;
    schDays: string;
    schFrequency: string;
    schManual: string;
    schType: string;
    schWeekDays: string;
    schWeeks: string;
    scheduleFrom: string;
    scheduleTo: string;
    syncAt: string;
    tagId: string;
    tagNumber: string;
    unit: string;
    unitId: string;
    area: string;
    areaId: string;
    latitude: string;
    longitude: string;
    created_at: string;
    deleted_at: string;
    date: string;
    assetCategoryId: string;
    assetCategoryName: string;
    assetForm: string;
    idschedule: string;
}
